#!/usr/bin/python3

"""
A daemon to maintain gobetween services in sync with OpenSVC
cluster services.

Services can set the following keywords in their env section
to configure the corresponding gobetween server:

* igw_gobtw_target_lb
* igw_gobtw_bind
* igw_gobtw_protocol
* igw_gobtw_balance
* igw_gobtw_max_connections
* igw_gobtw_client_idle_timeout
* igw_gobtw_backend_idle_timeout
* igw_gobtw_backend_connection_timeout
* igw_gobtw_sni
* igw_gobtw_tls
* igw_gobtw_backends_tls
* igw_gobtw_udp
* igw_gobtw_access
* igw_gobtw_proxy_protocol
* igw_gobtw_discovery_failpolicy
* igw_gobtw_discovery_kind
* igw_gobtw_discovery_srv_dns_protocol
* igw_gobtw_discovery_srv_lookup_server
* igw_gobtw_discovery_srv_lookup_pattern
* igw_gobtw_discovery_interval
* igw_gobtw_discovery_timeout
* igw_gobtw_healthcheck_fails
* igw_gobtw_healthcheck_passes
* igw_gobtw_healthcheck_interval
* igw_gobtw_healthcheck_kind
* igw_gobtw_healthcheck_timeout

"""
from __future__ import print_function

import traceback
import contextlib
import time
import sys
import os
import json
import socket
import optparse
import copy
import re

import requests

HOSTNAME = socket.gethostname().lower()
HEADERS = {
    "content-type": "application/json"
}

KEYWORD_PROXY = {
    "igw_gobtw_bind": "bind",
    "igw_gobtw_protocol": "protocol",
    "igw_gobtw_balance": "balance",
    "igw_gobtw_max_connections": "max_connections",
    "igw_gobtw_client_idle_timeout": "client_idle_timeout",
    "igw_gobtw_backend_idle_timeout": "backend_idle_timeout",
    "igw_gobtw_backend_connection_timeout": "backend_connection_timeout",
    "igw_gobtw_sni": "sni",
    "igw_gobtw_tls": "tls",
    "igw_gobtw_backends_tls": "backends_tls",
    "igw_gobtw_udp": "udp",
    "igw_gobtw_access": "access",
    "igw_gobtw_proxy_protocol": "proxy_protocol",
    "igw_gobtw_discovery_failpolicy": ["discovery", "failpolicy"],
    "igw_gobtw_discovery_kind": ["discovery", "kind"],
    "igw_gobtw_discovery_srv_dns_protocol": ["discovery", "srv_dns_protocol"],
    "igw_gobtw_discovery_srv_lookup_server": ["discovery", "srv_lookup_server"],
    "igw_gobtw_discovery_srv_lookup_pattern": ["discovery", "srv_lookup_pattern"],
    "igw_gobtw_discovery_interval": ["discovery", "interval"],
    "igw_gobtw_discovery_timeout": ["discovery", "timeout"],
    "igw_gobtw_healthcheck_fails": ["healthcheck", "fails"],
    "igw_gobtw_healthcheck_passes": ["healthcheck", "passes"],
    "igw_gobtw_healthcheck_interval": ["healthcheck", "interval"],
    "igw_gobtw_healthcheck_kind": ["healthcheck", "kind"],
    "igw_gobtw_healthcheck_timeout": ["healthcheck", "timeout"]
}

GOBETWEEN_DATA = {
    "bind": None,
    "protocol": "tcp",
    "balance": "weight",
    "max_connections": 0,
    "client_idle_timeout": "0",
    "backend_idle_timeout": "0",
    "backend_connection_timeout": "0",
    "sni": None,
    "tls": None,
    "backends_tls": None,
    "udp": None,
    "access": None,
    "proxy_protocol": None,
    "discovery": {
        "failpolicy": "keeplast",
        "kind": "srv",
        "srv_dns_protocol": "tcp",
        "srv_lookup_server": "",
        "srv_lookup_pattern": "",
        "interval": "5s",
        "timeout": "5s"
    },
    "healthcheck": {
        "fails": 1,
        "passes": 1,
        "interval": "2s",
        "kind": "ping",
        "timeout": "500ms"
    }
}

PORT_RANGE_LOW = 1024
PORT_RANGE_HIGH = 65535+1
REQ_TIMEOUT = 1
GOBTW_IP = "127.0.0.1"
GOBTW_PORT = 8888
DNS_PORT = '53'

class Error(Exception):
    """
    A known error handled by the daemon
    """
    pass

class LsnrReset(Exception):
    """
    Signals a OpenSVC listener socket issue (timeout, refused, ...)
    """
    pass

def bdecode(buff):
    """
    On python, convert bytes to string using utf-8 and ascii as a fallback
    """
    if buff is None:
        return buff
    if sys.version_info[0] < 3:
        return buff
    if isinstance(buff, str):
        return buff
    else:
        return buff.decode("utf-8", errors="ignore")
    return buff

def msg_encode(data):
    """
    Prepare a structure for sending on the OpenSVC listener socket.
    """
    return (json.dumps(data)+'\0').encode()

def msg_decode(message):
    """
    Decode a structure from a message received on the OpenSVC listener socket.
    """
    message = bdecode(message).rstrip("\0\x00")
    if len(message) == 0:
        return
    return json.loads(message)

def test_dict(dict1, dict2):
    """
    Return true if the dicts are not empty and have the same key/val in
    the first two hierachy levels.
    """
    if (dict1 == {}) or (dict2 == {}):
        print("dict empty")
        return False
    dict_to_del = dict2.copy()
    for key, val in dict1.items():
        if key in dict_to_del:
            if val == dict_to_del[key]:
                del dict_to_del[key]
    return dict_to_del == {}

class GoBetweenProxy(object):
    """
    The daemon class.
    """
    daemon_status_data = None

    @contextlib.contextmanager
    def lsnr_socket(self):
        """
        A context wrapper yield a socket to the OpenSVC listener,
        taking care of the clean up.
        """
        if "OPENSVC_LSNR_SOCK" in os.environ:
            lsnr_path = os.environ["OPENSVC_LSNR_SOCK"]
        elif os.path.exists("/var/run/lsnr/lsnr.sock"):
            lsnr_path = "/var/run/lsnr/lsnr.sock"
        else:
            lsnr_path = "/var/lib/opensvc/lsnr/lsnr.sock"

        try:
            lsnr = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            lsnr.settimeout(1)
            lsnr.connect(lsnr_path)
            yield lsnr
        finally:
            lsnr.close()

    @staticmethod
    def recv_message(sock, stream=False):
        """
        Receives a single or a stream of messages from the OpenSVC
        listener. Return them as a list.
        """
        chunks = []
        messages = []
        sep = b"\x00"
        while True:
            try:
                chunk = sock.recv(4096)
            except socket.timeout:
                break
            if stream and chunk == b'':
                # disconnect
                raise LsnrReset
            if not chunk or chunk == sep:
                break
            chunks.append(chunk)

        if sys.version_info[0] >= 3:
            data = b"".join(chunks)
        else:
            data = "".join(chunks)
        if len(data) == 0:
            return []
        for message in data.split(sep):
            message = msg_decode(message)
            messages.append(message)
        return messages

    def gobtw_status(self):
        """
        Get the GoBetween daemon status from the rest API.
        """
        return requests.get(self.url + "/", timeout=self.req_timeout).json()

    def gobtw_get_servers(self):
        """
        Get the GoBetween servers status from the Rest API.
        """
        data = requests.get(self.url + "/servers", timeout=self.req_timeout)
        if data.status_code != 200:
            raise Error("couldn't retrieve the data")
        return data.json()

    def url_service(self, svc):
        """
        Format and return the GoBetween Rest API url to the 'server'
        object.
        """
        return "%s/servers/%s" % (self.url, svc)

    def osvc_service_set_bind(self, svcname, val):
        """
        Submit to the OpenSVC listener a service configuration set action
        to change the env.igw_gobtw_bind value.
        """
        with self.lsnr_socket() as lsnr:
            lsnr.sendall(msg_encode({
                "action": "service_action",
                "options": {
                    "svcname": svcname,
                    "cmd": ["set", "--kw=env.igw_gobtw_bind=%s" % val],
                    "sync": True
                }
            }))

    def osvc_service_config(self, svcname):
        """
        Request the OpenSVC listener for a service configuration.
        """
        with self.lsnr_socket() as lsnr:
            lsnr.sendall(msg_encode({
                "action": "get_service_config",
                "options": {
                    "svcname": svcname,
                    "format": "json",
                    "evaluate": True
                }
            }))
            return self.recv_message(lsnr)[0]

    def osvc_service_env_section(self, svcname):
        """
        Return the OpenSVC "env" section of a given service.
        """
        return self.osvc_service_config(svcname)["env"]

    def osvc_cluster_config(self):
        """
        Request the OpenSVC listener for the cluster configuration.
        """
        with self.lsnr_socket() as lsnr:
            lsnr.sendall(msg_encode({
                "action": "get_node_config",
                "options": {
                    "format": "json",
                    "evaluate": True
                }
            }))
            return self.recv_message(lsnr)[0]

    def get_dns(self):
        """
        Get the ip addresses the DNS are listening on.
        """
        return self.osvc_cluster_config()['cluster']['dns'].split(" ")

    def get_dns_available(self):
        """
        Get the available DNS.
        """
        dns = self.get_dns()
        fqdn = ""
        for elem in dns:
            try:
                fqdn = socket.gethostbyaddr(elem)
            except socket.herror:
                continue
            if fqdn:
                break
        if not fqdn:
            print("no dns available")
        else:
            return fqdn

    def get_gobtw_srv_lookup_server(self):
        """
        Return the first DNS available.
        """
        if not self.get_dns_available():
            return
        return self.get_dns_available()[2][0]

    def get_service_expose(self, svcname):
        """
        Get the list of exposed parameters of a service.
        """
        expose = {}
        binds = self.osvc_service_env_section(svcname)["igw_gobtw_bind"].split()
        # example binds:
        # - 8080/tcp
        # - 8005/tcp-0.0.0.0:1105
        trash = [] 
        for bind in binds:
            try:
                back, front = bind.split("-")
            except ValueError:
                back = bind
                front = None
            try:
                port, protocol = back.split("/")
                port = int(port)
            except ValueError:
                print("service %s misformatted bind: %s" % (svcname, bind))
                trash.append(bind)
                continue
            expose[(port, protocol)] = front
        if trash:
            new_binds = list(set(binds) - set(trash))
            set_env = " ".join(new_binds)
            self.osvc_service_set_bind(svcname, set_env)
            time.sleep(1) 
        return expose

    def get_service_app(self, svcname):
        """
        Get the name of a service's app.
        """
        for nodes in self.daemon_status_data["monitor"]["nodes"].keys():
            app = self.daemon_status_data["monitor"]["nodes"][nodes]["services"]["status"][svcname]["app"]
        return app

    def get_cluster(self):
        """
        Return the clustername.
        """
        return self.daemon_status_data["cluster"]["name"].rstrip(".")

    def get_gobtw_srv_lookup_pattern(self, svcname):
        """
        Return a list of SRV records.
        """
        srv_lookup_pattern = []
        expose = self.get_service_expose(svcname)
        if not expose or not self.get_service_app(svcname) or not self.get_cluster():
            return
        for port, protocol in expose:
            srv_lookup_pattern.append("_%d._%s.%s.%s.svc.%s." % (port, protocol, svcname, self.get_service_app(svcname), self.get_cluster()))
        return srv_lookup_pattern

    @staticmethod
    def check_mandatory_keys(svcname, data):
        """
        Check that the mandatory keys are configured, if not raise an error.
        """
        mandatory = None

        if data["bind"] is None:
            print("service '%s' mandatory key: BIND, missing in data" % svcname)
            mandatory = True

        if data["discovery"]["srv_lookup_server"] == "":
            print("service '%s' mandatory key: SRV_LOOKUP_SERVER, missing in data" % svcname)
            mandatory = True

        if data["discovery"]["srv_lookup_pattern"] == "":
            print("service '%s' mandatory key: SRV_LOOKUP_PATTERN, missing in data" % svcname)
            mandatory = True

        if mandatory:
            raise Error

    @staticmethod
    def get_used_ports(data):
        """
        Return the ports already used by the configured services.
        """
        ports = []
        for elem in data:
            bind = data[elem]["bind"].split(" ")
            for elem2 in bind:
                port = int(elem2.split(":")[-1])
                ports.append(port)
        return ports

    @staticmethod
    def port_range():
        """
        Returns the list of usable ports.
        """
        return range(PORT_RANGE_LOW, PORT_RANGE_HIGH)

    def add_services_lb(self, svcname, dns_port=DNS_PORT):
        """
        Add or update a service to the GoBetween configuration through API Rest.
        """
        srv_lookup_pattern = self.get_gobtw_srv_lookup_pattern(svcname)
        if not srv_lookup_pattern:
            print("service '%s': IGW_GOBTW_BIND keyword erroneous syntax" % svcname)
            return
        for srv_records in srv_lookup_pattern:
            current_igw_bind = []
            server = "%s_%s" % (srv_records.split(".")[0], svcname)
            url_service = self.url_service(server)
            protocol = srv_records.split(".")[1][1:]
            port = int(srv_records.split(".")[0][1:])
            seek = "%d/%s" % (port, protocol)
            data = copy.deepcopy(GOBETWEEN_DATA)
            data["discovery"]["srv_lookup_pattern"] = srv_records
            if "dns_port" in self.osvc_service_env_section(svcname):
                dns_port = self.osvc_service_env_section(svcname)["dns_port"]
            data["discovery"]["srv_lookup_server"] = "%s:%s" % (self.get_gobtw_srv_lookup_server(), dns_port)
            for key, val in self.osvc_service_env_section(svcname).items():
                if key not in KEYWORD_PROXY:
                    continue
                if isinstance(KEYWORD_PROXY[key], list):
                    data[KEYWORD_PROXY[key][0]][KEYWORD_PROXY[key][1]] = val
                elif key == "igw_gobtw_bind":
                    current_igw_bind = val.split(" ")
                    binding = val.split(" ")
                    for elem in binding:
                        if seek in elem:
                            if "-" not in elem:
                                print("service '%s' addr not filled, binding one by default" % server)
                                data[KEYWORD_PROXY[key]] = "0.0.0.0:*"
                            else:
                                data[KEYWORD_PROXY[key]] = elem.split("-")[1]
                else:
                    data[KEYWORD_PROXY[key]] = val
            # test whether or not we should update the service conf in gobetween

            current_data = self.gobtw_get_servers()

            if server in current_data:
                if test_dict(current_data[server], data):
                    print("service '%s' is already configured" % server)
                    continue
                else:
                    print("service '%s' delete gobtwn server for re-add" % server)
                    try:
                        result = requests.delete(url_service, timeout=self.req_timeout)
                        if result.status_code != 200:
                            raise Error("couldn't delete current service configuration")
                        del current_data[server]
                    except Exception:
                        return

            try:
                self.check_mandatory_keys(server, data)
            except Error:
                return

            # make sure you are binding on a free port or auto alloc if no port configured
            used_ports = self.get_used_ports(current_data)
            if "*" in data["bind"]:
                addr = data["bind"].split(":")[0]
                port = None
                for port in self.port_range():
                    if port not in used_ports:
                        break
                data["bind"] = "%s:%d" % (addr, port)
                for elem in current_igw_bind:
                    if seek in elem:
                        if "-" not in elem:
                            new_elem = elem + "-" + data["bind"]
                            current_igw_bind[current_igw_bind.index(elem)] = new_elem
                        else:
                            new_elem = elem.replace(elem.split("-")[1], data["bind"])
                            current_igw_bind[current_igw_bind.index(elem)] = new_elem
                set_env = " ".join(current_igw_bind)
                self.osvc_service_set_bind(svcname, set_env)
                time.sleep(1)


            else:
                addr, port = data["bind"].split(":")
                port = int(port)
                if port in used_ports:
                    print("service '%s' defined port '%d' is busy, assign a free port" % (server, port))
                    for port in self.port_range():
                        if port not in used_ports:
                            break
                    data["bind"] = "%s:%d" % (addr, port)
                    for elem in current_igw_bind:
                        if seek in elem:
                            if "-" not in elem:
                                new_elem = elem + "-" + data["bind"]
                                current_igw_bind[current_igw_bind.index(elem)] = new_elem
                            else:
                                new_elem = elem.replace(elem.split("-")[1], data["bind"])
                                current_igw_bind[current_igw_bind.index(elem)] = new_elem
                    set_env = " ".join(current_igw_bind)
                    self.osvc_service_set_bind(svcname, set_env)
                    time.sleep(1)

            print("service '%s' add gobtwn server" % server)
            result = requests.post(url_service, data=json.dumps(data),
                                   headers=HEADERS, timeout=self.req_timeout)
            if result.status_code != 200:
                raise Error("failed to post %s: %s" % (url_service, result.status_code))

    def del_gobtw(self, svcname):
        url_service = self.url_service(svcname)
        del_service = requests.delete(url_service, timeout=self.req_timeout)
        if del_service.status_code != 200:
            raise Error("couldn't delete the service configuration")

    def del_services_lb(self, svcname):
        """
        Delete a service to the GoBetween configuration through API Rest.
        """
        print("service '%s' delete gobtwn server" % svcname)
        gobtw_servers = self.gobtw_get_servers()
        for serv in gobtw_servers:
            if re.match("_[0-9]+_"+svcname, serv):
                self.del_gobtw(serv)

    def gobtw_current_servers(self, svcname):
        """
        Deleting services whether it's necessary in order to be in sync with the OpenSVC configuration file.
        """
        current_servers = []
        srv_lookup_pattern = self.get_gobtw_srv_lookup_pattern(svcname)
        if srv_lookup_pattern:
            for elem in srv_lookup_pattern:
                server = "%s_%s" % (elem.split(".")[0], svcname)
                current_servers.append(server)
        gobtw_servers = self.gobtw_get_servers()
        for serv in gobtw_servers:
            if not re.match("_[0-9]+_"+svcname, serv):
                continue
            if serv not in current_servers or not current_servers:
                print("service '%s' no longer exists, deleting it" % serv)
                self.del_gobtw(serv)

    @staticmethod
    def parse_change(change):
        """
        Fetch any changes in OpenSVC services through the listener.
        """
        change_len = len(change)
        if change_len == 2:
            key = change[0]
            if len(key) == 3 and \
               key[0] == "services" and \
               key[1] == "status":
                return key[2], "add"
            elif len(key) == 4 and \
               key[0] == "services" and \
               key[1] == "config" and \
               key[3] == "updated":
                return key[2], "update"
        elif change_len == 1:
            key = change[0]
            if len(key) == 3 and \
               key[0] == "services" and \
               key[1] == "status":
                return key[2], "delete"
        return None, None

    @staticmethod
    def service_needs_lb(config):
        """
        Return True whether a service needs load balancing.
        """
        target = config.get("env", {}).get("igw_gobtw_target_lb", "").lower().split()
        if target and HOSTNAME not in target:
            return False
        if not config.get("env", {}).get("igw_gobtw_bind"):
            return False
        return True

    def event_router(self, data):
        """
        Trigger the action when it's required.
        """
        if data is None:
            return
        changes = data.get("data", {})
        valid_changes = []
        for change in changes:
            svcname, evt = self.parse_change(change)
            if evt is None and svcname is None:
                continue
            if evt is None or svcname is None:
                print("unexpected event: service '%s' %s event" % (svcname, evt))
                continue
            valid_changes.append((svcname, evt))

        if not valid_changes:
            return

        for svcname, evt in [elem for elem in valid_changes if elem[0] != "add"]:
            self.do_action(svcname, evt)
        self.osvc_daemon_status()
        for svcname, evt in [elem for elem in valid_changes if elem[0] == "add"]:
            self.do_action(svcname, evt)

    def do_action(self, svcname, evt):
        """
        Do a peculiar action in compliance with the corresponding event.
        """
        if self.is_scaler_slave(svcname):
            print("ignore scaler slave '%s' %s event" % (svcname, evt))
            return

        print("service '%s' %s event" % (svcname, evt))

        if evt == "add":
            config = self.osvc_service_config(svcname)
            if self.service_needs_lb(config):
                self.add_services_lb(svcname)
            else:
                print("service '%s' doesn't enable load balancing" % svcname)
        elif evt == "update":
            config = self.osvc_service_config(svcname)
            if self.service_needs_lb(config):
                self.add_services_lb(svcname)
                self.gobtw_current_servers(svcname)
            else:
                print("service '%s' no longer enables load balancing" % svcname)
                self.del_services_lb(svcname)
        elif evt == "delete":
            self.del_services_lb(svcname)

    def is_scaler_slave(self, svcname):
        """
        Return True whether a service is a scaler slave.
        """
        for ndata in self.daemon_status_data["monitor"]["nodes"].values():
            if ndata is None:
                continue
            if svcname not in ndata.get("services", {}).get("status", {}):
                continue
            sdata = ndata["services"]["status"][svcname]
            if sdata.get("scaler_slave"):
                return True
        return False

    def osvc_daemon_status(self):
        """
        Request the OpenSVC listener to get the daemon status.
        """
        with self.lsnr_socket() as lsnr:
            if lsnr is None:
                raise Error("lsnr socket not ready")
            lsnr.sendall(msg_encode({"action": "daemon_status"}))
            data = self.recv_message(lsnr)[0]
            if data is None:
                print("unable to get opensvc daemon data")
                return
            self.daemon_status_data = data

    def init_services(self):
        """
        Initialise service configuration in GoBetween.
        """
        self.osvc_daemon_status()
        for svcname, sdata in self.daemon_status_data["monitor"]["services"].items():
            if self.is_scaler_slave(svcname):
                continue
            config = self.osvc_service_config(svcname)
            if not self.service_needs_lb(config):
                print("service '%s' doesn't enable load balancing" % svcname)
                continue
            self.add_services_lb(svcname)

    def mainloop(self, lsnr):
        """
        Mainloop where we listen to the server events.
        """
        messages = self.recv_message(lsnr, stream=True)
        for message in messages:
            self.event_router(message)

    def set_options(self, **kwargs):
        """
        Parser for command line options.
        """
        options_data = [
            {
                "kwarg": "gobtw_port",
                "default": GOBTW_PORT,
            },
            {
                "kwarg": "gobtw_addr",
                "default": GOBTW_IP,
            },
            {
                "kwarg": "req_timeout",
                "default": REQ_TIMEOUT,
            },
        ]
        for odata in options_data:
            if kwargs[odata["kwarg"]] is not None:
                setattr(self, odata["kwarg"], kwargs[odata["kwarg"]])
            else:
                setattr(self, odata["kwarg"], odata["default"])
            print("init: %s = %s" % (odata["kwarg"], str(getattr(self, odata["kwarg"]))))
        self.url = "http://%s:%d" % (self.gobtw_addr, self.gobtw_port)

    def main(self, **kwargs):
        """
        Main function.
        """
        self.set_options(**kwargs)
        while True:
            try:
                self._main()
            except (LsnrReset, Error) as exc:
                print(exc)
                time.sleep(1)
            except KeyboardInterrupt:
                print("keyboard interrupt")
                break
            except Exception:
                traceback.print_exc()
                time.sleep(1)

    def _main(self):
        """
        Infinite loop where we use the event_router() function.
        """
        last_gobtw_status = {}
        with self.lsnr_socket() as lsnr:
            lsnr.sendall(msg_encode({"action": "events"}))
            if lsnr is None:
                raise LsnrReset("lsnr socket not ready")
            self.init_services()
            while True:
                try:
                    new_gobtw_status = self.gobtw_status()
                    if last_gobtw_status == {} or \
                       new_gobtw_status["startTime"] != last_gobtw_status["startTime"]:
                        last_gobtw_status = new_gobtw_status
                        self.init_services()
                except Exception as exc:
                    print("get gobtw status error: %s" % str(exc), file=sys.stderr)
                self.mainloop(lsnr)

if __name__ == "__main__":
    parser = optparse.OptionParser()
    parser.add_option("-p", "--port", action="store",
                      dest="gobtw_port", help="The GoBetween Rest API port. default %d" % GOBTW_PORT)
    parser.add_option("-a", "--addr", action="store",
                      dest="gobtw_addr", help="The GoBetween Rest API address. default %s" % GOBTW_IP)
    parser.add_option("--req-timeout", action="store", type="int",
                      dest="req_timeout", help="The timeout of GoBetween Rest API requests. default %d" % REQ_TIMEOUT)
    options, _ = parser.parse_args()
    options = vars(options)
    try:
        obj = GoBetweenProxy()
        obj.main(**options)
    except KeyboardInterrupt:
        pass
